# Butler deep coadds
Ref: [Deep coadds](https://dp1.lsst.io/tutorials/notebook/202/notebook-202-1.html)

In [1]:
from lsst.daf.butler import Butler, Timespan
import lsst.afw.display as afwDisplay
from astropy.time import Time
import pandas as pd

butler = Butler("dp1", collections="LSSTComCam/DP1")
assert butler is not None

bands = ['u', 'g', 'r', 'i', 'z', 'y']
fields = pd.read_csv('LSSTComCam_fields.csv', index_col='field')
fields

                ra_deg  dec_deg
field
47Tuc             6.02   -72.08
LELF_SV_38_7     37.86     6.98
Fornax           40.00   -34.45
ECDFS            53.13   -28.10
EDFS             59.10   -48.73
LGLF_SV_95_-25   95.00   -25.00
Seagull_Nebula  106.23   -10.51

In [2]:
df = pd.DataFrame(columns = ['field', 'band'])
for field in fields.index:
    for band in bands:
        query = "band.name = '{}' AND patch.region OVERLAPS POINT({}, {})".\
                format(band, fields.loc[field, 'ra_deg'], fields.loc[field, 'dec_deg'])
        try:
            dataset_refs = butler.query_datasets("deep_coadd", where=query)
            deep_coadd = butler.get(dataset_refs[0])
            df.loc[len(df)] = [field, band]
        except Exception as exc:
            print(field, exc)
df

47Tuc Possible reasons for empty result:

47Tuc Possible reasons for empty result:

LELF_SV_38_7 Possible reasons for empty result:

LELF_SV_38_7 Possible reasons for empty result:

Fornax Possible reasons for empty result:

Fornax Possible reasons for empty result:

Fornax Possible reasons for empty result:

Seagull_Nebula Possible reasons for empty result:

Seagull_Nebula Possible reasons for empty result:

             field band
0            47Tuc    g
1            47Tuc    r
2            47Tuc    i
3            47Tuc    y
4     LELF_SV_38_7    g
5     LELF_SV_38_7    r
6     LELF_SV_38_7    i
7     LELF_SV_38_7    z
8           Fornax    g
9           Fornax    r
10          Fornax    i
11           ECDFS    u
12           ECDFS    g
13           ECDFS    r
14           ECDFS    i
15           ECDFS    z
16           ECDFS    y
17            EDFS    u
18            EDFS    g
19            EDFS    r
20            EDFS    i
21            EDFS    z
22            EDFS    y
23  LGLF_SV_95_-25    u
24  LGLF_SV_95_-25    g
25  LGLF_SV_95_-25    r
26  LGLF_SV_95_-25    i
27  LGLF_SV_95_-25    z
28  LGLF_SV_95_-25    y
29  Seagull_Nebula    u
30  Seagull_Nebula    g
31  Seagull_Nebula    r
32  Seagull_Nebula    z

In [3]:
afwDisplay.setDefaultBackend("firefly")

def grabdeep_coadd(field, band):
    query = "band.name = '{}' AND patch.region OVERLAPS POINT({}, {})".\
    format(band, fields.loc[field, 'ra_deg'], fields.loc[field, 'dec_deg'])
    print(query)
    dataset_refs = butler.query_datasets("deep_coadd", where=query)
    return butler.get(dataset_refs[0])
            
def firefly(idx):
    field = df.loc[idx, 'field']
    band = df.loc[idx, 'band']
    deep_coadd = grabdeep_coadd(field, band)
    deep_coadd.writeFits(f'butler_deep_coadd_{band}_{field}.fits')
    afw_display = afwDisplay.Display(frame=1)
    afw_display.mtv(deep_coadd)
    afw_display.setMaskTransparency(100)
    return deep_coadd

In [4]:
for idx in df.index:
    firefly(idx)

band.name = 'g' AND patch.region OVERLAPS POINT(6.02, -72.08)
band.name = 'r' AND patch.region OVERLAPS POINT(6.02, -72.08)
band.name = 'i' AND patch.region OVERLAPS POINT(6.02, -72.08)
band.name = 'y' AND patch.region OVERLAPS POINT(6.02, -72.08)
band.name = 'g' AND patch.region OVERLAPS POINT(37.86, 6.98)
band.name = 'r' AND patch.region OVERLAPS POINT(37.86, 6.98)
band.name = 'i' AND patch.region OVERLAPS POINT(37.86, 6.98)
band.name = 'z' AND patch.region OVERLAPS POINT(37.86, 6.98)
band.name = 'g' AND patch.region OVERLAPS POINT(40.0, -34.45)
band.name = 'r' AND patch.region OVERLAPS POINT(40.0, -34.45)
band.name = 'i' AND patch.region OVERLAPS POINT(40.0, -34.45)
band.name = 'u' AND patch.region OVERLAPS POINT(53.13, -28.1)
band.name = 'g' AND patch.region OVERLAPS POINT(53.13, -28.1)
band.name = 'r' AND patch.region OVERLAPS POINT(53.13, -28.1)
band.name = 'i' AND patch.region OVERLAPS POINT(53.13, -28.1)
band.name = 'z' AND patch.region OVERLAPS POINT(53.13, -28.1)
band.name = 'y' AND patch.region OVERLAPS POINT(53.13, -28.1)
band.name = 'u' AND patch.region OVERLAPS POINT(59.1, -48.73)
band.name = 'g' AND patch.region OVERLAPS POINT(59.1, -48.73)
band.name = 'r' AND patch.region OVERLAPS POINT(59.1, -48.73)
band.name = 'i' AND patch.region OVERLAPS POINT(59.1, -48.73)
band.name = 'z' AND patch.region OVERLAPS POINT(59.1, -48.73)
band.name = 'y' AND patch.region OVERLAPS POINT(59.1, -48.73)
band.name = 'u' AND patch.region OVERLAPS POINT(95.0, -25.0)
band.name = 'g' AND patch.region OVERLAPS POINT(95.0, -25.0)
band.name = 'r' AND patch.region OVERLAPS POINT(95.0, -25.0)
band.name = 'i' AND patch.region OVERLAPS POINT(95.0, -25.0)
band.name = 'z' AND patch.region OVERLAPS POINT(95.0, -25.0)
band.name = 'y' AND patch.region OVERLAPS POINT(95.0, -25.0)
band.name = 'u' AND patch.region OVERLAPS POINT(106.23, -10.51)
band.name = 'g' AND patch.region OVERLAPS POINT(106.23, -10.51)
band.name = 'r' AND patch.region OVERLAPS POINT(106.23, -10.51)
band.name = 'z' AND patch.region OVERLAPS POINT(106.23, -10.51)