# Data Preview 1 (DP1) Tutorials: a summary
Ref: [DP1 Tutorials](https://dp1.lsst.io/tutorials/index.html)

In [1]:
import glob
import pandas as pd

# grep all ipynb in DP1 for 
# - LSST data products
# - Packages

tut_path = '../tutorial-notebooks/DP1'
files = sorted(glob.glob(f'{tut_path}/**/*.ipynb', recursive=True))

cols = ['L0', 'L1', 'ipynb']
dprod = pd.DataFrame(columns=cols)  # these are the 12 tables under Schema Browser > Data Preview 1 on https://sdm-schemas.lsst.io/dp1.html
dpack = pd.DataFrame(columns=cols)
for nfile, file in enumerate(files):
    dprod.loc[nfile, cols] = file.split('/')[3:]
    dpack.loc[nfile, cols] = file.split('/')[3:]
    with open(file) as fp:
        lines = fp.read().splitlines()
    nline = 0
    while 'LSST data products' not in lines[nline]:
        nline += 1
    for nn in range(1, lines[nline].count('`'), 2):
        tis = lines[nline].split('`')[nn].replace('object', 'Object')
        dprod.loc[nfile, tis] = True
    nline = 0
    while 'Packages' not in lines[nline]:
        nline += 1
    for nn in range(1, lines[nline].count('`'), 2):
        dpack.loc[nfile, lines[nline].split('`')[nn]] = True
# dprod.fillna(' ', inplace=True)
# dpack.fillna(' ', inplace=True)
dpack.drop(columns=['numpy', 'matplotlib', 'scipy', 'astropy'], inplace=True)
assert (dpack[cols] == dprod[cols]).all().all()
dprod

,L0,L1,ipynb,Object,ForcedSourceOnDiaObject,Visit,DiaSource,SSSource,deep_coadd,visit_image,...,template_coadd,raw,bias,dark,flat,the_monster_20250219,deepCoadd,visit_detector_table,skymap,coadd
0,100_How_to_Use_RSP_Tools,101_JupyterLab_and_Notebooks,101_1_Use_the_JupyterLab.ipynb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100_How_to_Use_RSP_Tools,101_JupyterLab_and_Notebooks,101_2_Use_a_Notebook.ipynb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100_How_to_Use_RSP_Tools,102_Catalog_access,102_1_Get_started_with_TAP.ipynb,True,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100_How_to_Use_RSP_Tools,102_Catalog_access,102_2_Catalog_queries_with_TAP.ipynb,True,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100_How_to_Use_RSP_Tools,102_Catalog_access,102_3_Table_joins_with_TAP.ipynb,NaN,True,True,True,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,300_Science_Demos,306_Extragalactic_transients,306_2_Candidate_transient_identification.ipynb,NaN,True,True,NaN,NaN,NaN,True,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,300_Science_Demos,306_Extragalactic_transients,306_3_Cross_match_queries.ipynb,NaN,True,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,300_Science_Demos,307_AGN,307_1_AGN_Light_Curves.ipynb,True,True,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,300_Science_Demos,308_Solar_System,308_1_Discoveries.ipynb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,300_Science_Demos,308_Solar_System,308_2_Orbits.ipynb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
dprod.columns

Index(['L0', 'L1', 'ipynb', 'Object', 'ForcedSourceOnDiaObject', 'Visit',
       'DiaSource', 'SSSource', 'deep_coadd', 'visit_image', 'source',
       'visit_summary', 'direct_warp', 'visit_table',
       'deep_coadd_predetection', 'CcdVisit', 'Source', 'ForcedSource',
       'DiaObject', 'SSObject', 'MPCORB', 'visit_images', 'difference_image',
       'template_coadd', 'raw', 'bias', 'dark', 'flat', 'the_monster_20250219',
       'deepCoadd', 'visit_detector_table', 'skymap', 'coadd'],
      dtype='object')

* 11 out of 12 catalogs found:
Object
Source
ForcedSourceOnDiaObject
DiaObject
DiaSource
ForcedSource
SSObject
SSSource
MPCORB
Visit
CcdVisit
(missing CoaddPatches)

* 5 image categories:
deep_coadd
template_coadd
visit_image
difference_image
raw

source
object
visit_summary
direct_warp
visit_table
deep_coadd_predetection
visit_images
bias
dark
flat
the_monster_20250219
deepCoadd
visit_detector_table
skymap
coadd

In [5]:
dprod.loc[dprod['Object']==True][['L0', 'L1', 'ipynb']]

,L0,L1,ipynb
2,100_How_to_Use_RSP_Tools,102_Catalog_access,102_1_Get_started_with_TAP.ipynb
3,100_How_to_Use_RSP_Tools,102_Catalog_access,102_2_Catalog_queries_with_TAP.ipynb
5,100_How_to_Use_RSP_Tools,102_Catalog_access,102_4_Retrieve_job_by_URL.ipynb
14,100_How_to_Use_RSP_Tools,104_Butler_data_access,104_4_Catalog_queries_with_the_butler.ipynb
17,100_How_to_Use_RSP_Tools,105_Image_reprocessing,105_3_Forced_Photometry.ipynb
19,100_How_to_Use_RSP_Tools,105_Image_reprocessing,105_5_Background_subtraction.ipynb
23,200_Data_Products,201_Catalogs,201_1_Object_table.ipynb
42,200_Data_Products,205_Point_Spread_Function_PSF,205_2_PSF_coadded_images.ipynb
44,300_Science_Demos,301_Field_explorations,301_1_47Tuc_Globular_Cluster.ipynb
45,300_Science_Demos,301_Field_explorations,301_2_Low_Ecliptic_Latitude.ipynb
46,300_Science_Demos,301_Field_explorations,301_3_Fornax_Dwarf_Spheroidal_Galaxy.ipynb
47,300_Science_Demos,301_Field_explorations,301_4_Extended_Chandra_Deep_Field_South.ipynb
49,300_Science_Demos,301_Field_explorations,301_6_Low_Galactic_Latitude_Field.ipynb
50,300_Science_Demos,301_Field_explorations,301_7_Seagull_Nebula.ipynb
51,300_Science_Demos,303_Galaxies,303_1_Galaxy_photometry.ipynb
52,300_Science_Demos,304_Cosmology,304_1_PSF_for_cosmology.ipynb
53,300_Science_Demos,304_Cosmology,304_2_Abell360_red_sequence.ipynb
58,300_Science_Demos,307_AGN,307_1_AGN_Light_Curves.ipynb

In [14]:
dprod.loc[(dprod['source']==True) | (dprod['Source']==True)].dropna(axis=1, how='all')

,L0,L1,ipynb,visit_image,source,object,Source,visit_images,coadd
14,100_How_to_Use_RSP_Tools,104_Butler_data_access,104_4_Catalog_queries_with_the_butler.ipynb,NaN,True,True,NaN,NaN,NaN
24,200_Data_Products,201_Catalogs,201_2_Source_table.ipynb,NaN,NaN,NaN,True,NaN,NaN
41,200_Data_Products,205_Point_Spread_Function_PSF,205_1_PSF_visit_images.ipynb,True,True,NaN,NaN,NaN,NaN
52,300_Science_Demos,304_Cosmology,304_1_PSF_for_cosmology.ipynb,NaN,True,True,NaN,True,True

In [15]:
dpack.loc[(dprod['source']==True) | (dprod['Source']==True)].dropna(axis=1, how='all')

,L0,L1,ipynb,lsst.rsp.get_tap_service,lsst.daf.butler,lsst.rsp,lsst.afw.display,lsst.geom,treecorr
14,100_How_to_Use_RSP_Tools,104_Butler_data_access,104_4_Catalog_queries_with_the_butler.ipynb,NaN,True,NaN,NaN,NaN,NaN
24,200_Data_Products,201_Catalogs,201_2_Source_table.ipynb,NaN,True,True,NaN,NaN,NaN
41,200_Data_Products,205_Point_Spread_Function_PSF,205_1_PSF_visit_images.ipynb,True,True,True,True,True,NaN
52,300_Science_Demos,304_Cosmology,304_1_PSF_for_cosmology.ipynb,NaN,True,NaN,NaN,NaN,True

In [2]:
dpack

,L0,L1,ipynb,lsst.rsp.get_tap_service,retrieve_query,lsst.daf.butler,lsst.rsp.utils,lsst.rsp.service,pyvo.dal,lsst.afw.image,...,lsst.source.injection,skyproj,lsst.geom,lsst.rsp.retrieve_query,lsst.rsp.get_tap_service,treecorr,lsst.utils.plotting,lsst.afw,lsst.resources,pyvo.dal.adhoc
0,100_How_to_Use_RSP_Tools,101_JupyterLab_and_Notebooks,101_1_Use_the_JupyterLab.ipynb,,,,,,,,...,,,,,,,,,,
1,100_How_to_Use_RSP_Tools,101_JupyterLab_and_Notebooks,101_2_Use_a_Notebook.ipynb,,,,,,,,...,,,,,,,,,,
2,100_How_to_Use_RSP_Tools,102_Catalog_access,102_1_Get_started_with_TAP.ipynb,True,,,,,,,...,,,,,,,,,,
3,100_How_to_Use_RSP_Tools,102_Catalog_access,102_2_Catalog_queries_with_TAP.ipynb,True,,,,,,,...,,,,,,,,,,
4,100_How_to_Use_RSP_Tools,102_Catalog_access,102_3_Table_joins_with_TAP.ipynb,True,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,300_Science_Demos,306_Extragalactic_transients,306_2_Candidate_transient_identification.ipynb,,,,,,,,...,,,True,,,,True,True,True,True
57,300_Science_Demos,306_Extragalactic_transients,306_3_Cross_match_queries.ipynb,,,,,,,,...,,,,,,,,True,,
58,300_Science_Demos,307_AGN,307_1_AGN_Light_Curves.ipynb,,,,,,,,...,,,,,,,True,,,
59,300_Science_Demos,308_Solar_System,308_1_Discoveries.ipynb,,,,,,,,...,,,,,,,,,,
60,300_Science_Demos,308_Solar_System,308_2_Orbits.ipynb,,,,,,,,...,,,,,,,,,,

In [3]:
dpack.columns

Index(['L0', 'L1', 'ipynb', 'lsst.rsp.get_tap_service', 'retrieve_query',
       'lsst.daf.butler', 'lsst.rsp.utils', 'lsst.rsp.service', 'pyvo.dal',
       'lsst.afw.image', 'lsst.rsp', 'lsst.afw.display', 'pyvo',
       'lsst.ctrl.mpexec', 'lsst.pipe.base', 'lsst.drp.tasks',
       'lsst.meas.algorithms', 'lsst.meas.base', 'lsst.pipe.tasks',
       'lsst.source.injection', 'skyproj', 'lsst.geom',
       'lsst.rsp.retrieve_query', 'lsst.rsp.get_tap_service ', 'treecorr',
       'lsst.utils.plotting', 'lsst.afw', 'lsst.resources', 'pyvo.dal.adhoc'],
      dtype='object')

In [16]:
dpack.loc[dpack['lsst.rsp.get_tap_service']==True]

,L0,L1,ipynb,lsst.rsp.get_tap_service,retrieve_query,lsst.daf.butler,lsst.rsp.utils,lsst.rsp.service,pyvo.dal,lsst.afw.image,...,lsst.source.injection,skyproj,lsst.geom,lsst.rsp.retrieve_query,lsst.rsp.get_tap_service,treecorr,lsst.utils.plotting,lsst.afw,lsst.resources,pyvo.dal.adhoc
2,100_How_to_Use_RSP_Tools,102_Catalog_access,102_1_Get_started_with_TAP.ipynb,True,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100_How_to_Use_RSP_Tools,102_Catalog_access,102_2_Catalog_queries_with_TAP.ipynb,True,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100_How_to_Use_RSP_Tools,102_Catalog_access,102_3_Table_joins_with_TAP.ipynb,True,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,100_How_to_Use_RSP_Tools,102_Catalog_access,102_4_Retrieve_job_by_URL.ipynb,True,True,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,200_Data_Products,204_Calibrations,204_2_The_Monster.ipynb,True,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN
41,200_Data_Products,205_Point_Spread_Function_PSF,205_1_PSF_visit_images.ipynb,True,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN